version: '2'
services:
  sensor_app:
    image: ${IMAGE_NAME}
    container_name: sensor
    ports:
    - "8080:8080"
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - BUCKET_NAME=${BUCKET_NAME}